---
- name: Create .env file
  template:
    src: .env.j2
    dest: "{{ playbook_dir }}/../../../app/.env"
    mode: '0644'

- name: Set storage directory permissions
  file:
    path: "{{ playbook_dir }}/../../../app/storage"
    state: directory
    mode: '0777'
    recurse: yes

- name: Set bootstrap/cache directory permissions
  file:
    path: "{{ playbook_dir }}/../../../app/bootstrap/cache"
    state: directory
    mode: '0777'
    recurse: yes

- name: Configure PHP settings
  template:
    src: php.ini.j2
    dest: "{{ playbook_dir }}/../../../docker/php.ini"
    mode: '0644' 