name: Destroy Infrastructure

on:
  workflow_dispatch:  # Permite ejecución manual desde GitHub

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  TF_VAR_rds_password: ${{ secrets.RDS_PASSWORD }}
  VPC_NAME: "car-wizard-vpc"

jobs:
  terraform-destroy:
    name: Destroy Infrastructure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Force Delete ECS Resources
        run: |
          echo "Eliminando servicios ECS..."
          CLUSTER_NAME="car-wizard-cluster"
          SERVICE_NAME="car-wizard-service"
          
          # Verificar si el cluster existe
          CLUSTER_EXISTS=$(aws ecs describe-clusters --clusters $CLUSTER_NAME --query 'clusters[0].status' --output text 2>/dev/null || echo "INACTIVE")
          
          if [ "$CLUSTER_EXISTS" != "INACTIVE" ]; then
            echo "Cluster encontrado, procediendo con la eliminación de servicios..."
            
            # Verificar si el servicio existe
            SERVICE_EXISTS=$(aws ecs list-services --cluster $CLUSTER_NAME --query 'serviceArns[0]' --output text 2>/dev/null || echo "")
            
            if [ ! -z "$SERVICE_EXISTS" ] && [ "$SERVICE_EXISTS" != "None" ]; then
              echo "Servicio encontrado, procediendo con la eliminación..."
              
              # Escalar el servicio a 0
              aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --desired-count 0 || true
              
              # Esperar a que los tasks se detengan (máximo 5 minutos)
              timeout=300
              while [ $timeout -gt 0 ]; do
                TASKS=$(aws ecs list-tasks --cluster $CLUSTER_NAME --service-name $SERVICE_NAME --query 'taskArns' --output text)
                if [ -z "$TASKS" ] || [ "$TASKS" == "None" ]; then
                  break
                fi
                echo "Esperando que los tasks se detengan... ($timeout segundos restantes)"
                sleep 10
                timeout=$((timeout-10))
              done
              
              # Forzar eliminación de tareas restantes
              TASKS=$(aws ecs list-tasks --cluster $CLUSTER_NAME --query 'taskArns[]' --output text) || true
              if [ ! -z "$TASKS" ] && [ "$TASKS" != "None" ]; then
                echo "Forzando eliminación de tareas..."
                for TASK in $TASKS; do
                  aws ecs stop-task --cluster $CLUSTER_NAME --task $TASK --reason "Destroy infrastructure" || true
                done
              fi
              
              # Eliminar el servicio
              echo "Eliminando servicio ECS..."
              aws ecs delete-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --force || true
            else
              echo "No se encontró el servicio ECS, continuando..."
            fi
            
            # Eliminar el cluster
            echo "Eliminando cluster ECS..."
            aws ecs delete-cluster --cluster $CLUSTER_NAME || true
          else
            echo "No se encontró el cluster ECS, continuando..."
          fi

      - name: Force Delete Lambda Resources
        run: |
          echo "Eliminando recursos de Lambda..."
          # Eliminar permisos y triggers primero
          aws events remove-targets --rule trigger-car-data-update --ids TriggerLambda || true
          aws events delete-rule --name trigger-car-data-update || true
          aws lambda delete-function --function-name LoadDataLambda || true

      - name: Force Delete Load Balancer
        run: |
          echo "Eliminando Load Balancer..."
          # Obtener ARN del ALB
          ALB_ARN=$(aws elbv2 describe-load-balancers --names car-wizard-alb --query 'LoadBalancers[0].LoadBalancerArn' --output text) || true
          if [ ! -z "$ALB_ARN" ] && [ "$ALB_ARN" != "None" ]; then
            # Eliminar listeners
            LISTENERS=$(aws elbv2 describe-listeners --load-balancer-arn $ALB_ARN --query 'Listeners[*].ListenerArn' --output text) || true
            for listener in $LISTENERS; do
              aws elbv2 delete-listener --listener-arn $listener || true
            done
            # Eliminar el ALB
            aws elbv2 delete-load-balancer --load-balancer-arn $ALB_ARN || true
          fi
          
          # Eliminar target groups
          TG_ARN=$(aws elbv2 describe-target-groups --names car-wizard-tg --query 'TargetGroups[0].TargetGroupArn' --output text) || true
          if [ ! -z "$TG_ARN" ] && [ "$TG_ARN" != "None" ]; then
            aws elbv2 delete-target-group --target-group-arn $TG_ARN || true
          fi

      - name: Clean up ECR Repository
        if: always()
        run: |
          echo "Limpiando repositorio ECR..."
          REPO_NAME="car-wizard"
          aws ecr list-images --repository-name $REPO_NAME --query 'imageIds[*]' --output json | \
          jq -r '.[] | [.imageDigest] | @tsv' | \
          while read digest; do
            aws ecr batch-delete-image --repository-name $REPO_NAME --image-ids imageDigest=$digest || true
          done
          aws ecr delete-repository --repository-name $REPO_NAME --force || true

      - name: Force Delete RDS Resources
        run: |
          echo "Eliminando recursos de RDS..."
          
          # Eliminar instancia RDS
          DB_IDENTIFIER="car-wizard-db"
          echo "Eliminando instancia RDS $DB_IDENTIFIER..."
          aws rds delete-db-instance --db-instance-identifier $DB_IDENTIFIER --skip-final-snapshot --delete-automated-backups || true
          
          # Esperar a que la instancia se elimine (máximo 20 minutos)
          echo "Esperando a que la instancia RDS se elimine..."
          timeout=1200
          while [ $timeout -gt 0 ]; do
            DB_STATUS=$(aws rds describe-db-instances --db-instance-identifier $DB_IDENTIFIER --query 'DBInstances[0].DBInstanceStatus' --output text 2>/dev/null || echo "deleted")
            if [ "$DB_STATUS" == "deleted" ] || [ "$DB_STATUS" == "None" ]; then
              echo "Instancia RDS eliminada"
              break
            fi
            echo "Estado de RDS: $DB_STATUS ($timeout segundos restantes)"
            sleep 30
            timeout=$((timeout-30))
          done
          
          # Eliminar subnet groups
          echo "Eliminando DB subnet groups..."
          aws rds delete-db-subnet-group --db-subnet-group-name car-wizard-rds-subnet-group || true
          
          # Eliminar parameter groups
          echo "Eliminando DB parameter groups..."
          aws rds delete-db-parameter-group --db-parameter-group-name $(aws rds describe-db-parameter-groups --query 'DBParameterGroups[?starts_with(DBParameterGroupName, `car-wizard-params-`)].DBParameterGroupName' --output text) || true

      - name: Force Delete Network Resources
        run: |
          echo "Eliminando recursos de red..."
          
          # Obtener VPC ID
          VPC_ID=$(aws ec2 describe-vpcs --filters "Name=tag:Name,Values=${VPC_NAME}" --query 'Vpcs[0].VpcId' --output text)
          
          if [ ! -z "$VPC_ID" ] && [ "$VPC_ID" != "None" ]; then
            echo "Eliminando recursos asociados a VPC $VPC_ID..."
            
            # Esperar a que el ALB se elimine completamente
            echo "Esperando que el ALB se elimine completamente..."
            sleep 90
            
            # Verificar y eliminar ECS Tasks
            echo "Verificando tareas ECS..."
            CLUSTER_NAME="car-wizard-cluster"
            TASKS=$(aws ecs list-tasks --cluster $CLUSTER_NAME --query 'taskArns[]' --output text) || true
            if [ ! -z "$TASKS" ] && [ "$TASKS" != "None" ]; then
              echo "Deteniendo tareas ECS..."
              for TASK in $TASKS; do
                aws ecs stop-task --cluster $CLUSTER_NAME --task $TASK --reason "Destroy infrastructure" || true
              done
              echo "Esperando que las tareas se detengan..."
              sleep 60
            fi

            # Buscar y eliminar ENIs, con reintentos
            for attempt in {1..3}; do
              echo "Intento $attempt de eliminar Network Interfaces..."
              ENIs=$(aws ec2 describe-network-interfaces --filters "Name=vpc-id,Values=$VPC_ID" --query 'NetworkInterfaces[*].NetworkInterfaceId' --output text) || true
              if [ ! -z "$ENIs" ] && [ "$ENIs" != "None" ]; then
                for eni in $ENIs; do
                  echo "Intentando desasociar ENI $eni..."
                  ATTACHMENT=$(aws ec2 describe-network-interfaces --network-interface-ids $eni --query 'NetworkInterfaces[0].Attachment.AttachmentId' --output text) || true
                  if [ ! -z "$ATTACHMENT" ] && [ "$ATTACHMENT" != "None" ]; then
                    aws ec2 detach-network-interface --attachment-id $ATTACHMENT --force || true
                    sleep 10
                  fi
                  echo "Intentando eliminar ENI $eni..."
                  aws ec2 delete-network-interface --network-interface-id $eni || true
                done
                echo "Esperando 30 segundos antes del siguiente intento..."
                sleep 30
              else
                echo "No se encontraron ENIs para eliminar"
                break
              fi
            done
            
            # Eliminar NAT Gateways
            echo "Eliminando NAT Gateways..."
            NAT_GATEWAYS=$(aws ec2 describe-nat-gateways --filter "Name=vpc-id,Values=$VPC_ID" --query 'NatGateways[*].NatGatewayId' --output text) || true
            for nat in $NAT_GATEWAYS; do
              aws ec2 delete-nat-gateway --nat-gateway-id $nat || true
            done
            
            if [ ! -z "$NAT_GATEWAYS" ]; then
              echo "Esperando que los NAT Gateways se eliminen..."
              sleep 45
            fi
            
            # Eliminar Endpoints
            echo "Eliminando VPC Endpoints..."
            VPC_ENDPOINTS=$(aws ec2 describe-vpc-endpoints --filters "Name=vpc-id,Values=$VPC_ID" --query 'VpcEndpoints[*].VpcEndpointId' --output text) || true
            for endpoint in $VPC_ENDPOINTS; do
              aws ec2 delete-vpc-endpoints --vpc-endpoint-ids $endpoint || true
            done
            
            # Eliminar Security Groups, con reintentos
            for attempt in {1..3}; do
              echo "Intento $attempt de eliminar Security Groups..."
              SEC_GROUPS=$(aws ec2 describe-security-groups --filters "Name=vpc-id,Values=$VPC_ID" "Name=group-name,Values=!default" --query 'SecurityGroups[*].GroupId' --output text) || true
              if [ ! -z "$SEC_GROUPS" ] && [ "$SEC_GROUPS" != "None" ]; then
                for sg in $SEC_GROUPS; do
                  aws ec2 delete-security-group --group-id $sg || true
                done
                sleep 20
              else
                break
              fi
            done
            
            # Eliminar Route Tables
            echo "Eliminando Route Tables..."
            ROUTE_TABLES=$(aws ec2 describe-route-tables --filters "Name=vpc-id,Values=$VPC_ID" --query 'RouteTables[?Associations[0].Main!=`true`].RouteTableId' --output text) || true
            for rt in $ROUTE_TABLES; do
              # Eliminar rutas no principales
              aws ec2 describe-route-tables --route-table-id $rt --query 'RouteTables[0].Routes[?Origin!=`CreateRouteTable`].DestinationCidrBlock' --output text | while read -r cidr; do
                if [ ! -z "$cidr" ]; then
                  aws ec2 delete-route --route-table-id $rt --destination-cidr-block $cidr || true
                fi
              done
              
              # Desasociar
              ASSOC_IDS=$(aws ec2 describe-route-tables --route-table-ids $rt --query 'RouteTables[*].Associations[*].RouteTableAssociationId' --output text) || true
              for assoc in $ASSOC_IDS; do
                aws ec2 disassociate-route-table --association-id $assoc || true
              done
              
              aws ec2 delete-route-table --route-table-id $rt || true
            done
            
            # Eliminar Internet Gateway
            IGW_ID=$(aws ec2 describe-internet-gateways --filters "Name=attachment.vpc-id,Values=$VPC_ID" --query 'InternetGateways[*].InternetGatewayId' --output text) || true
            if [ ! -z "$IGW_ID" ] && [ "$IGW_ID" != "None" ]; then
              aws ec2 detach-internet-gateway --internet-gateway-id $IGW_ID --vpc-id $VPC_ID || true
              sleep 15
              aws ec2 delete-internet-gateway --internet-gateway-id $IGW_ID || true
            fi
            
            # Eliminar Subnets con reintentos
            for attempt in {1..3}; do
              echo "Intento $attempt de eliminar Subnets..."
              SUBNETS=$(aws ec2 describe-subnets --filters "Name=vpc-id,Values=$VPC_ID" --query 'Subnets[*].SubnetId' --output text) || true
              if [ ! -z "$SUBNETS" ] && [ "$SUBNETS" != "None" ]; then
                for subnet in $SUBNETS; do
                  aws ec2 delete-subnet --subnet-id $subnet || true
                done
                sleep 30
              else
                break
              fi
            done
            
            # Esperar y mostrar recursos restantes antes de intentar eliminar la VPC
            echo "Esperando 45 segundos antes de eliminar la VPC..."
            sleep 45
            
            echo "Verificando recursos restantes en la VPC..."
            echo "ENIs restantes:"
            aws ec2 describe-network-interfaces --filters "Name=vpc-id,Values=$VPC_ID" || true
            echo "Security Groups restantes:"
            aws ec2 describe-security-groups --filters "Name=vpc-id,Values=$VPC_ID" || true
            echo "Subnets restantes:"
            aws ec2 describe-subnets --filters "Name=vpc-id,Values=$VPC_ID" || true
            
            # Intentar eliminar la VPC
            echo "Intentando eliminar la VPC..."
            aws ec2 delete-vpc --vpc-id $VPC_ID || true
            
            if [ $? -ne 0 ]; then
              echo "No se pudo eliminar la VPC. Por favor, revisa la consola de AWS para más detalles."
            fi
          fi

      - name: Force Delete Service Roles
        run: |
          echo "Eliminando roles de servicio..."
          
          # Lista de roles de servicio (excluyendo GHActionsRole)
          SERVICE_ROLES=(
            "LambdaExecutionRole"
            "ecsTaskExecutionRole"
          )
          
          for ROLE_NAME in "${SERVICE_ROLES[@]}"; do
            echo "Procesando rol: $ROLE_NAME"
            
            # Obtener y eliminar políticas inline
            INLINE_POLICIES=$(aws iam list-role-policies --role-name $ROLE_NAME --query 'PolicyNames[*]' --output text) || true
            for POLICY in $INLINE_POLICIES; do
              echo "Eliminando política inline $POLICY del rol $ROLE_NAME"
              aws iam delete-role-policy --role-name $ROLE_NAME --policy-name $POLICY || true
            done
            
            # Desasociar políticas administradas
            ATTACHED_POLICIES=$(aws iam list-attached-role-policies --role-name $ROLE_NAME --query 'AttachedPolicies[*].PolicyArn' --output text) || true
            for POLICY_ARN in $ATTACHED_POLICIES; do
              echo "Desvinculando política $POLICY_ARN del rol $ROLE_NAME"
              aws iam detach-role-policy --role-name $ROLE_NAME --policy-arn $POLICY_ARN || true
            done
            
            # Eliminar el rol
            echo "Eliminando rol $ROLE_NAME"
            aws iam delete-role --role-name $ROLE_NAME || true
          done

      - name: Force Delete CloudWatch Logs
        run: |
          echo "Eliminando grupos de logs de CloudWatch..."
          
          # Eliminar grupo de logs de Lambda
          aws logs delete-log-group --log-group-name "/aws/lambda/LoadDataLambda" || true
          
          # Eliminar grupos de logs de ECS
          LOG_GROUPS=$(aws logs describe-log-groups --log-group-name-prefix "/ecs/car-wizard-" --query 'logGroups[*].logGroupName' --output text) || true
          for log_group in $LOG_GROUPS; do
            echo "Eliminando grupo de logs $log_group..."
            aws logs delete-log-group --log-group-name "$log_group" || true
          done

      - name: Terraform Destroy
        working-directory: terraform
        run: terraform destroy -auto-approve
        env:
          TF_VAR_rds_password: ${{ secrets.RDS_PASSWORD }}